CREATE DATABASE bookdb;
USE Bookdb;
CREATE TABLE books (BookID INT PRIMARY KEY, BookName TEXT, Ratings FLOAT);
INSERT INTO books VALUES (1, "To Kill a Mockingbird", 4.27 );
INSERT INTO books VALUES (2, "1984", 4.19 );
INSERT INTO books VALUES (3, "The Lord of the Rings", 4.52 );
INSERT INTO books VALUES (4, "The Catcher in the Rye", 3.82 );
INSERT INTO books VALUES (5, "The Great Gatsby", 3.93 );
INSERT INTO books VALUES (6, "The Lion, the Witch and the Wardrobe", 4.23 );
INSERT INTO books VALUES (7, "The Lord of the Flies", 3.69 );
INSERT INTO books VALUES (8, "The Return of the King (The Lord of the Rings, #3)", 4.55 );
INSERT INTO books VALUES (9, "Harry Potter and the Deathly Hallows (Harry Potter, #7)", 4.62 );
INSERT INTO books VALUES (10, "	The Nightingale", 4.60 );
INSERT INTO books VALUES (11, "	Harry Potter and the Prisoner of Azkaban (Harry Potter, #3)", 4.58);
INSERT INTO books VALUES (12, "	Harry Potter and the Half-Blood Prince (Harry Potter, #6)", 4.58 );
INSERT INTO books VALUES (13, "The Last Olympian (Percy Jackson and the Olympians, #5)", 4.53 );
INSERT INTO books VALUES (14, "Harry Potter and the Order of the Phoenix (Harry Potter, #5)", 4.50 );
INSERT INTO books VALUES (15, "Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones", 4.38 );
INSERT INTO books VALUES (16, "The Subtle Art of Not Giving a F*ck: A Counterintuitive Approach to Living a Good Life", 3.91);
INSERT INTO books VALUES (17, "How to Win Friends and Influence People", 4.22 );
INSERT INTO books VALUES (18, "The 7 Habits of Highly Effective People: Powerful Lessons in Personal Change", 4.15 );
INSERT INTO books VALUES (19, "The Power of Habit: Why We Do What We Do in Life and Business", 4.13);
INSERT INTO books VALUES (20, "The Life-Changing Magic of Tidying Up: The Japanese Art of Decluttering and Organizing ", 3.87 );
INSERT INTO books VALUES (21, "You Are a Badass: How to Stop Doubting Your Greatness and Start Living an Awesome Life", 3.95 );
INSERT INTO books VALUES (22 ,"The Power of Now: A Guide to Spiritual Enlightenment", 4.15 );
INSERT INTO books VALUES (23, "Quiet: The Power of Introverts in a World That Can't Stop Talking", 4.07 );
INSERT INTO books VALUES (24, "Think and Grow Rich", 4.18 );
INSERT INTO books VALUES (25, "Rich Dad, Poor Dad", 4.12);
INSERT INTO books VALUES (26, "The 4-Hour Workweek", 3.92 );
INSERT INTO books VALUES (27, "The Alchemist", 3.90 );
INSERT INTO books VALUES (28, "The 48 Laws of Power", 4.15 );
INSERT INTO books VALUES (29, "Eat That Frog!: 21 Great Ways to Stop Procrastinating and Get More Done in Less Time", 3.87);
INSERT INTO books VALUES (30, "How to Stop Worrying and Start Living ", 4.15 );
SELECT * FROM books;
